project:
  type: website

website:
  title: "Course Template"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: fa-home
      - href: about.qmd
        text: About
      - href: setup.qmd
        text: Setup
        icon: fa-gear

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



